### ISSUE TITLE
Create intermediate output directories

### ISSUE THREAD

**Issue by trymnilsen** [Tienisto/flutter-fast-i18n#53]
**Motivation**
If a different output directory than the input directory is defined, and any of these directories does not exist an error will be thrown.

```
Generating translations...

Found build.yaml in /Users/.../code/app/build.yaml

 -> fileType: json
 -> baseLocale: en
 -> fallbackStrategy: baseLocale
 -> inputDirectory: /Users/.../code/app/strings
 -> inputFilePattern: .i18n.json
 -> outputDirectory: /Users/.../code/app/lib/i18n
 -> outputFilePattern (deprecated): .g.dart
 -> outputFileName: null
 -> outputFileFormat: multipleFiles
 -> renderLocaleHandling: true
 -> namespaces: false
 -> translateVar: t
 -> enumName: AppLocale
 -> translationClassVisibility: private
 -> keyCase: null (no change)
 -> keyCase (for maps): null (no change)
 -> paramCase: null (no change)
 -> stringInterpolation: dart
 -> renderFlatMap: true
 -> renderTimestamp: true
 -> maps: []
 -> pluralization/auto: cardinal
 -> pluralization/cardinal: []
 -> pluralization/ordinal: []
 -> contexts: no custom contexts
 -> interfaces: no interfaces

Found base name: "strings" (used for output file name and class names)
Scanning translations...

   (base) en -> /Users/.../code/app/strings/strings.i18n.json
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/.../code/app/lib/i18n/strings.g.dart' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      generateTranslations (file:///Users/.../flutter/.pub-cache/hosted/pub.dartlang.org/fast_i18n-5.10.0/bin/fast_i18n.dart:341:10)
<asynchronous suspension>
#5      main (file:///Users/.../flutter/.pub-cache/hosted/pub.dartlang.org/fast_i18n-5.10.0/bin/fast_i18n.dart:47:5)
<asynchronous suspension>
pub finished with exit code 255
```

There should either be a more descriptive error, or the ability to create the intermediate output directories (in this case the `i18n` directory inside `lib`).

**Developer Experience**
A field in build.yaml can control if directories should be turned on

**Comment by Tienisto** [comment]
Fixed in fc8c8d26752391e771e6296c53af10308c5d5a59
